# Generated by Django 4.2.3 on 2023-07-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='student_photos'),
        ),
    ]
