# Generated by Django 4.2.3 on 2023-07-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_student_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user']},
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='student_photos/'),
        ),
    ]
