# Generated by Django 4.2.3 on 2023-07-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='media/default.jpeg', upload_to='student_photos/'),
        ),
    ]
