# Generated by Django 4.2.3 on 2023-07-30 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_student_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='photo',
            new_name='picture',
        ),
    ]
