# Generated by Django 4.2.3 on 2023-08-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_photo_student_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
