# Generated by Django 4.2.3 on 2023-08-02 21:34

import WebApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_student_course'),
        ('WebApp', '0002_studentgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255, verbose_name=WebApp.models.StudentGroup)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.student')),
            ],
        ),
    ]
