# Generated by Django 4.2.3 on 2023-07-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('WebApp', '0002_alter_registration_student_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='courses',
        ),
        migrations.AddField(
            model_name='module',
            name='groups',
            field=models.ManyToManyField(related_name='modules', to='auth.group'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
