# Generated by Django 4.2.3 on 2023-08-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_alter_course_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='groups',
            field=models.ManyToManyField(related_name='modules', to='WebApp.studentgroup'),
        ),
    ]
